Algoritmo "Codigo do pedido"
// Escrever um algoritmo que leia o código do item pedido, a quantidade e calcule o valor a ser pago por aquele lanche.

Var
//
c:real
v:real
q:real

Inicio
//
escreval("Digite o código do pedido")
leia(c)
escreval("Digite o valor do produto")
leia(v)
escreval("Digite a quantidade")
leia(q)
escreval("O valor a ser pago é:", v*q ,"reais")

Fimalgoritmo