Algoritmo "ex1"
//
Elaborar um algoritmo para os valores a e b abaixo, que escreva sua soma, subtração, divisão e multiplicação. Utilizando variáveis.
a = 10
b = 5


Var
//

a,b:inteiro

Inicio
//

a<-10
b<-5
escreval("O valor da soma é:", a+b)
escreval("O valor da subtração é:", a-b)
escreval("O valor da divisão é:", a/b)
escreval("O valor da multiplicação é:", a*b)

Fimalgoritmo
