Algoritmo "hipotenusa"

//Faça um algoritmo que o usuário informe os valores dos catetos de um triângulo retângulo e que ao
//final escreva a sua hipotenusa.

Var
//
cateto1, cateto2: real
hipotenusa: real
total: real

Inicio
//

escreva ("escreva cateto1", cateto1)
leia (cateto1)
escreva ("escreva cateto2", cateto2)
leia (cateto2)

hipotenusa <- cateto1 + cateto2 / 2
escreva ("hipotenusa", hipotenusa)

Fimalgoritmo