Algoritmo "quadrado"

//Elabore um algoritmo que leia o tamanho do lado de um quadrado e informe a área e o perímetro
//do quadrado.(Perímetro = 4 * L; área = L ^ 2)

Var
//

lado: inteiro
area: inteiro
perimetro: inteiro
total: real

Inicio
//
escreval("Valor do lado:")
leia (lado)
area <- lado * lado
perimetro <- 4 * lado

escreva ("area", area)
leia (area)

escreva ("perimetro", perimetro)
leia (perimetro)



Fimalgoritmo